title: Jupyter Guide to Climate Data
author: DKRZ
logo: logo.png
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
# - references.bib
#

repository:
  url: https://github.com/cehbrecht/jupyter-guide-to-climate-data
  branch: main

launch_buttons:
  notebook_interface: "classic"
  colab_url: ""
  thebe: true  
