name: climate-guide
channels:
- conda-forge
dependencies:
- pip
- python>=3.7
# jupyter book  
- sphinx
- jupyter-book
# jupyter lab  
- jupyterlab
# publish book
- ghp-import
# cdo
- cdo
- python-cdo  
# esgf
- esgf-pyclient
# rooki  
- birdy
- beautifulsoup4
- pymetalink
- owslib
- pyproj>=3.0.1
# xarray 
- netcdf4
- xarray  
- dask
# plot
- matplotlib
- pip:
  - rooki
