name: climate-guide
channels:
- conda-forge
dependencies:
- pip
- python>=3.7
# jupyter book  
- sphinx
- jupyter-book
# jupyter lab  
- jupyterlab
# rooki  
- birdy
- beautifulsoup4
- pymetalink
- owslib
- pyproj>=3.0.1
# open xarray results
- netcdf4
- xarray  
- pip:
  - rooki
